POST http://localhost:8000/login/
Content-Type: application/json
    
    {
        "username": "ham",
        "password": "ham"
    }

###

POST http://localhost:8000/register/
Content-Type: application/json
    
    {
        "username": "hamlk",
        "password": "ham",
        "email": "admin@mail.com"
    }


###

GET http://localhost:8000/logout/
Content-Type: application/json
{}


###

POST http://localhost:8000/saveAnnotations/
Content-Type: application/json

    {
        "annotations": [
            {
                "id": 2,
                "x": 0.2,
                "y": 0.2,
                "width": 0.2,
                "height": 0.2,
                "label": "test",
                "image_id": 2
            }
        ]
    }

    