# Generated by Django 4.2.6 on 2023-10-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_user_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='users',
        ),
    ]
