# Generated by Django 3.2.5 on 2023-12-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_nlp_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlp_data',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
