# Generated by Django 3.2.5 on 2023-12-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_nlp_data_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlp_data',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
